### ISSUE TITLE
Multiple references to (non-existent) color coded text

### ISSUE THREAD

**Issue by W6HBR** [AllStarLink/ASL3-Manual#9]
The lines listed below in the SIP configuration page **[docs/adv-topics/sip-phone.md](https://github.com/AllStarLink/ASL3-Manual/blob/main/docs/adv-topics/sip-phone.md)** refer to color coding that does not exist.
 

The orange highlighted lines can be removed if you do not want the announcement.

The entry in blue is the extension number for your sip phone.

If you want to use a different extension number, you will need to update the items in yellow with your desired number. 

The item in orange should also be updated for your preferred caller identifier.

The items marked in blue should be updated to match the username and password you want for your extension number.

**Comment by tsawyer** [comment]
@KB4MDD Any progress on this?

**Comment by KB4MDD** [comment]
I am finishing up the rework of chan_tlb.  I will look at this next.
